version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - .:/app
    depends_on:
      - db # Si tienes una base de datos, por ejemplo